AWSTemplateFormatVersion: 2010-09-09
Resources:
  
  ArtifactsRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: my-repository
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - Sid: AllowPush
            Effect: Allow
            Principal: 
              # Fake account
              AWS: arn:aws:iam::00000000000:root
            Action: 
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
          - Sid: AllowPull
            Effect: Allow
            Principal:
              # Fake account
              AWS: arn:aws:iam::00000000000:root
            Action: 
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:GetAuthorizationToken
      LifecyclePolicy:
        LifecyclePolicyText:
          '{
            "rules": [
                {
                    "rulePriority": 1,
                    "selection": {
                        "tagStatus": "any",
                        "countType": "imageCountMoreThan",
                        "countNumber": 10
                    },
                    "action": {
                        "type": "expire"
                    }
                }
            ]
          }'
